@url= http://localhost:6501

### BASE
{{url}}


### GET Employees
{{url}}/employees



### ADD EMPLOYEE
POST {{url}}/employee
content-type: application/json

{
	"lastName": "Addington1010",
	"firstName": "Aubrey123",
	"title": "Sales Representative",
	"notes": "Author is a test employee that we are adding."
}


### GET Employee with ID
{{url}}/employee/63ebe34f25878bad04bc48c1

### DELETE Employee with ID
DELETE {{url}}/employee/63ebe34f25878bad04bc48c1

### EDIT EMPLOYEE
PATCH {{url}}/employee/63ebe34f25878bad04bc48c1
content-type: application/json

{
	"lastName": "Addington000",
	"firstName": "Aubreyas000",
	"title": "Sales Representative",
	"notes": "Author is a test employee that we are adding."
}