@url= http://localhost:6501

### BASE
{{url}}


### GET Employees
{{url}}/employees


### ADD EMPLOYEE
POST {{url}}/employee
content-type: application/json

{
	"lastName": "Addington55555200",
	"firstName": "Aubrey123",
	"title": "Sales Representative",
	"notes": "Author is a test employee that we are adding."
}


### GET Employee with ID
{{url}}/employee/63ebe866fee40b7a556ac93a

### DELETE Employee with ID
DELETE {{url}}/employee/63ebe82ffee40b7a556ac92c

### EDIT EMPLOYEE
PATCH {{url}}/employee/63ebe866fee40b7a556ac93a
content-type: application/json

{
	"lastName": "Addington Anton",
	"firstName": "Anton",
	"title": "Sales Anton",
	"notes": "Author is a test employee that we are adding."
}